# Generated by Django 2.2.12 on 2020-10-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=12, verbose_name='订单号')),
                ('specific_goods', models.CharField(max_length=20, verbose_name='具体物品')),
                ('goods_type', models.CharField(max_length=5, verbose_name='物品类别')),
                ('transport_mileage', models.FloatField(verbose_name='运送里程')),
                ('transport_type', models.CharField(max_length=5, verbose_name='运送类别')),
                ('transport_weight', models.FloatField(verbose_name='运送重量')),
                ('transport_volume', models.FloatField(verbose_name='运送体积')),
            ],
            options={
                'db_table': 'goods_info',
            },
        ),
        migrations.CreateModel(
            name='sender_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=12, verbose_name='电话')),
                ('city', models.CharField(max_length=20, verbose_name='城市/区域')),
                ('detailed_address', models.CharField(max_length=50, verbose_name='详细地址')),
                ('name_of_company', models.CharField(max_length=20, verbose_name='公司名称')),
                ('order_number', models.CharField(max_length=12, verbose_name='订单号')),
                ('recipient_sender', models.BooleanField(verbose_name='收发件人判断')),
            ],
            options={
                'db_table': 'rs_info',
            },
        ),
        migrations.CreateModel(
            name='transform_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_awb', models.CharField(max_length=20, verbose_name='运单号')),
                ('is_tradition', models.BooleanField(verbose_name='是否交付')),
                ('tradition_id', models.CharField(max_length=5, verbose_name='交付人')),
                ('is_distribution', models.BooleanField(verbose_name='是否确认接收配送')),
                ('distribution_id', models.CharField(max_length=5, verbose_name='接收人')),
            ],
            options={
                'db_table': 'tf_info',
            },
        ),
    ]
